'\" t
.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\" Copyright 2010 Sun Microsystems, Inc.  All rights reserved.
.\" Use is subject to license terms.
.\"
.\" ident "@(#)antlr2.3	1.2	10/03/16 SMI"
.\"
.\" This man page created by Sun to provide a reference to the html
.\" for antlr2 with the Drools distribution.
.\"
.TH antlr2 3 "4 Feb 2009"
.SH NAME
antlr2 \- (AN)other (T)ool for (L)anguage (R)ecognition 
.SH DESCRIPTION
antlr2(3) (AN)other (T)ool for (L)anguage (R)ecognition - formerly known as PCCTS - is a language tool that provides a framework for constructing recognizers, compilers, and translators from grammatical descriptions containing actions in the following languages: Java, C++, C# or Python.For additional information on using antlr2, browse the complete html documentation at:
.IP
.B file:/usr/share/doc/antlr-2.7.7/index.html 
.LP
.SH LICENSE
BSD
.SH FILES
/usr/share/antlr-2.7.7/antlr.jar
.IP
antlr2 jar file
.LP
/usr/share/doc/antlr-2.7.7/index.html 
.IP
antlr2 API documentation generated with javadoc. 
.LP
.SH ATTRIBUTES
See
.BR attributes (5)
for descriptions of the following attributes:
.sp
.TS
box;
cbp-1 | cbp-1
l | l .
ATTRIBUTE TYPE	ATTRIBUTE VALUE
=
Availability	developer/parser/antlr-2
=
Interface Stability	Uncommitted
.TE
.SH SEE ALSO
http://www.antlr2.org/
.SH NOTES
Source for antlr2 is available on http://opensolaris.org
